### PR TITLE
add NOP netdev as default

### PR DESCRIPTION
**Pull request by scottfeldman**
Initialize netdev to dummy NOP netdev that gracefully errors out all netdev interface calls.  This is to catch cases where useNetdev() was not called by the app to set netdev.

### CODE REVIEW

**Comment by leongross** [comment]
I think until https://github.com/tinygo-org/tinygo/pull/4273 is fully functional this is a good work for now

**Comment by leongross** [comment]
some gofumpt issues, but I just realized that there is no ci so feel free to ignore these nits :)

**Comment by deadprogram** [comment]
@scottfeldman could you please run `go fmt` on these changes?

**Comment by deadprogram** [comment]
Actually @leongross I ran gofmt and it did not find anything needing formatting.

Hence I will merge this now.

Thanks @scottfeldman

**Pull request merged**
